server:
  servlet:
    context-path: /
  port: 8081

spring:
  application:
    name: MES-SERVICE
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

swagger:
  host: http://localhost:8080

ribbon:
  ReadTimeout: 160000000
  ConnectTimeout: 160000000

eureka:
  instance:
    hostname: localhost

openapi:
  service:
    title: Sample service doc #title that you will want to display in the swagger ui
    version: 1.0.0
    url: http://localhost:8080/sample #api gateway url

springdoc:
  api-docs:
    path: /v3/api-docs #these urls will used to load the swagger ui of this service by the api gateway
  swagger-ui:
    path: /swagger-ui.html